//types pour le current Screen
export const TOGGLE_ASSO = "TOGGLE_ASSO";
export const UPDATE_CHECK_REQUEST = "UPDATE_CHECK_REQUEST";
export const UPDATE_CHECK_SUCCESS = "UPDATE_CHECK_SUCCESS";
export const UPDATE_CHECK_ERROR = "UPDATE_CHECK_ERROR";
export const TOGGLE_HEADER_BUTTON = "TOGGLE_HEADER_BUTTON";
export const TOGGLE_USER_PHOTO = "TOGGLE_USER_PHOTO";
export const UPDATE_FORCED_EVENTS = "UPDATE_FORCED_EVENTS";

//types pour les events
export const REFRESH_EVENTS_REQUEST = "REFRESH_EVENTS_REQUEST";
export const REFRESH_EVENTS_SUCCESS = "REFRESH_EVENTS_SUCCESS";
export const REFRESH_EVENTS_ERROR = "REFRESH_EVENTS_ERROR";

//types pour les assosData
export const GET_ASSOS_DATA_REQUEST = "GET_ASSOS_DATA_REQUEST";
export const GET_ASSOS_DATA_SUCCESS = "GET_ASSOS_DATA_SUCCESS";
export const GET_ASSOS_DATA_ERROR = "GET_ASSOS_DATA_ERROR";

//types pour les UserData
export const GET_USER_DATA_REQUEST = "GET_USER_DATA_REQUEST";
export const GET_USER_DATA_SUCCESS = "GET_USER_DATA_SUCCESS";
export const GET_USER_DATA_ERROR = "GET_USER_DATA_ERROR";

//types pour les promoted
export const REFRESH_PROMOTED_REQUEST = "REFRESH_PROMOTED_REQUEST";
export const REFRESH_PROMOTED_SUCCESS = "REFRESH_PROMOTED_SUCCESS";
export const REFRESH_PROMOTED_ERROR = "REFRESH_PROMOTED_ERROR";

//types pour la partie admissible
export const REFRESH_ADMISSIBLE_REQUEST = "REFRESH_ADMISSIBLE_REQUEST";
export const REFRESH_ADMISSIBLE_SUCCESS = "REFRESH_ADMISSIBLE_SUCCESS";
export const REFRESH_ADMISSIBLE_ERROR = "REFRESH_ADMISSIBLE_ERROR";
